version: "3.9"

services:
  db:
    image: postgres:13
    container_name: persian_clubhouse_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
  web:
    build: .
    container_name: persian_clubhouse_bot
    command: bash -c "
      python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000
      && python manage.py start_bot
      "
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
