# Generated by Django 3.2.2 on 2021-05-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('telegram_user_id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('telegram_username', models.CharField(db_index=True, max_length=250)),
                ('telegram_name', models.CharField(max_length=250)),
                ('clubhouse_user_id', models.CharField(db_index=True, max_length=250, null=True)),
                ('clubhouse_username', models.CharField(db_index=True, max_length=250, null=True)),
                ('clubhouse_phone_number', models.CharField(db_index=True, max_length=13)),
                ('clubhouse_auth_token', models.CharField(max_length=350)),
                ('instagram_username', models.CharField(max_length=350)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
